/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mhb_xhook_nativehook_HookManager */

#ifndef _Included_com_mhb_xhook_nativehook_HookManager
#define _Included_com_mhb_xhook_nativehook_HookManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mhb_xhook_nativehook_HookManager
 * Method:    initNativeHook
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mhb_xhook_nativehook_HookManager_initNativeHook
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
