/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mhb_xhook_networklib_NetworkLibInit */

#ifndef _Included_com_mhb_xhook_networklib_NetworkLibInit
#define _Included_com_mhb_xhook_networklib_NetworkLibInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mhb_xhook_networklib_NetworkLibInit
 * Method:    initNativeHook
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mhb_xhook_networklib_NetworkLibInit_initNativeHook
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
